"""empty message

Revision ID: 3990a030da05
Revises: df927184f068
Create Date: 2017-04-20 00:16:12.656018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3990a030da05'
down_revision = 'df927184f068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Status')
    # ### end Alembic commands ###
