"""empty message

Revision ID: 5c38ead0d5a3
Revises: e99d47117be3
Create Date: 2017-03-07 17:10:44.210056

"""

# revision identifiers, used by Alembic.
revision = '5c38ead0d5a3'
down_revision = 'e99d47117be3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Reports', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Reports')
    ### end Alembic commands ###
