"""empty message

Revision ID: 93531dc9a8a6
Revises: 3990a030da05
Create Date: 2017-04-20 00:19:47.476467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93531dc9a8a6'
down_revision = '3990a030da05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
