"""empty message

Revision ID: c72196f52aff
Revises: 
Create Date: 2017-04-20 00:06:01.594970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72196f52aff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Status', sa.String(length=10)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Status')
    # ### end Alembic commands ###
