"""empty message

Revision ID: dad74da176a9
Revises: None
Create Date: 2016-07-04 14:08:13.722137

"""

# revision identifiers, used by Alembic.
revision = 'dad74da176a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Motor', sa.Column('Picture', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'Motor', ['Asset Tag'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Motor', type_='unique')
    op.drop_column('Motor', 'Picture')
    ### end Alembic commands ###
