"""empty message

Revision ID: df927184f068
Revises: c72196f52aff
Create Date: 2017-04-20 00:15:58.305213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df927184f068'
down_revision = 'c72196f52aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
