"""empty message

Revision ID: e7f5a36ca1e7
Revises: 93531dc9a8a6
Create Date: 2017-04-20 00:19:59.215196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f5a36ca1e7'
down_revision = '93531dc9a8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'Status')
    # ### end Alembic commands ###
