"""empty message

Revision ID: e99d47117be3
Revises: 0006163443c4
Create Date: 2017-03-07 15:06:54.671328

"""

# revision identifiers, used by Alembic.
revision = 'e99d47117be3'
down_revision = '0006163443c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link_table', 'users', ['user_id'], ['id'])
    op.add_column('task', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'date')
    op.drop_constraint(None, 'link_table', type_='foreignkey')
    op.drop_column('link_table', 'user_id')
    ### end Alembic commands ###
